NumPy : 

NumPy is a python library used for working with arrays.

In [1]:
import numpy as np
arr = np.array([12,13,14])
print(arr)

[12 13 14]


In [2]:
#0-D Arrays

arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [3]:
#1-D Array

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [5]:
#2-D Array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("this is the dimension of the array ",arr.ndim)

[[1 2 3]
 [4 5 6]]
this is the dimension of the array  2


In [6]:
#3-D Array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,0,1]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 0 1]]]
3


Higher Dimensional Arrays

In [7]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [8]:
#indexing
arr = np.array([1,2,3,4])
print(arr[0])

1


Accessing

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [10]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,0,1]]])
print(arr[0,1,2])

6


Negative indexing

In [12]:
#print last element from 2nd dim:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [13]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-5:-3])

[3 4]


In [14]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [15]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


Slicing 2-D Arrays

From the second element,slice elements from index 1 to index 4.

In [16]:
arr = arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


Shape of an array

In [17]:
arr = arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [18]:
#Reshape of array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape from 1-D TO 3-D

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


NumPy  

1.Searching Arrays       
2.Search Sorted            
3.Search from the right side           
4.Multiple values             

In [20]:
#1.

#find the indexes where the value is 4:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [21]:
#2.

arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [22]:
#3.1

arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7, side='right')
print(x)

2


In [23]:
#3.2

arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7, side='left')
print(x)

1


In [24]:
#4.

arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


Numpy Aggregation function : 

aggregate function performns a calculation on a set of values, and returns a single value.

In [25]:
a=np.array([1,2,3,4,5])
print("a :",a)
sum=np.sum(a)
print("sum:",sum)
product=np.prod(a)
print("product :",product)
mean=np.mean(a)
print("mean :",mean)
standard_deviation=np.std(a)
print("standard_deviation :",standard_deviation)
variance=np.var(a)
print("variance:", variance)
minimum=np.min(a)
print("minimum value:",minimum)
maximum=np.max(a)
print("maximum value:",maximum)
minimum_index=np.argmin(a)
print("minimum index:",minimum_index)
maximum_index=np.argmax(a)
print("maximum index:",maximum_index)
median=np.median(a)
print("median:",median)


a : [1 2 3 4 5]
sum: 15
product : 120
mean : 3.0
standard_deviation : 1.4142135623730951
variance: 2.0
minimum value: 1
maximum value: 5
minimum index: 0
maximum index: 4
median: 3.0
